# Advanced test with 20 parallel pods
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../testrun-advanced.yaml

patches:
  - target:
      kind: TestRun
      name: k6-advanced-test
    patch: |-
      - op: replace
        path: /spec/parallelism
        value: 20

commonLabels:
  test.parallelism: "20"
