version: "3.8"
services:
  influxdb:
    image: influxdb:2.7
    ports: ["8086:8086"]
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminadmin
      DOCKER_INFLUXDB_INIT_ORG: perf-org
      DOCKER_INFLUXDB_INIT_BUCKET: k6
      DOCKER_INFLUXDB_INIT_RETENTION: 30d
    volumes:
      - influx-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:11.2.0
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      INFLUXDB_TOKEN: CkzuNUj6YWN_fhPkl-4iJjxYy5i8hXVh_tEqIzFL8-varNGTQu-j-7rw-HxG4FYPAgt_6skxtlhazyHaJ80rKw==
    volumes:
      - grafana-data:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards
    depends_on: [influxdb]
volumes:
  influx-data:
  grafana-data:
