# Basic test with 10 parallel pods
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../testrun-basic.yaml

patches:
  - target:
      kind: TestRun
      name: k6-basic-test
    patch: |-
      - op: replace
        path: /spec/parallelism
        value: 10

commonLabels:
  test.parallelism: "10"
