apiVersion: 1

datasources:
  - name: InfluxDB_k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: perf-org
      defaultBucket: k6
      tlsSkipVerify: true
    secureJsonData:
      token: $__env{INFLUXDB_TOKEN}
    isDefault: true
